### ISSUE TITLE
Write Admin Quickstart docs

### ISSUE THREAD

**Issue by nlMeminger** [jwflory/django-rit-grasa#122]
# Summary

Write documentation that someone who has never touched anything can effectively use and deploy the project and have it work

# Background

Related to #192. Get more background there.

# Details

Bolded lines are most important / should be most detailed:

- [x] ~~**Install dependencies (e.g. Docker/git/`git clone`)**~~
- [x] ~~Set up MariaDB database~~
- [x] ~~Config settings (@jwflory -- as a new page)~~ #234
- [x] ~~**`run.sh setup` -- see #133**~~ #243
- [x] ~~`run.sh start -p {80,443}` -- start container, optionally with custom port (see #133)~~
- [x] ~~**`http://sitename.org/initial_setup` -- explain what this/does**~~
- [x] ~~`run.sh stop` -- see #133~~

# Outcome

- Quick and easy to deploy the app for the first time
- Easier to support the app over time

**Comment by justwheel** [comment]
Tagging for completion in Sprint 5.

**Comment by justwheel** [comment]
_Discussed during 2019-11-13 ops meeting with @nlMeminger and @jwflory._

---

@nlMeminger and I mapped out what the admin quickstart guide should include. The specific sections of the one-page doc was added to the original comment as a checklist. We should have a draft ready over the weekend so we have time to review leading to next Tuesday's hand-off.

**Comment by justwheel** [comment]
Some refactoring done in #234. The only thing left to close this issue is a more detailed explanation of the container host set-up step.

**Comment by nlMeminger** [comment]
This should be finished with #243

**Comment by justwheel** [comment]
Completed in #243. Closing as complete. :ocean:
