### ISSUE TITLE
BE Story: Finish event edit system

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#154]
# Summary

Ensure editing system functionally works without triggering any bugs

# Background

The editing system is the last major component of our project to finish. There are a couple more pieces to tidy up before we're ready to ship this as a v1.0.0 release.

# Details

- [x] @nlMeminger ~All metadata of a event should appear in edit interface automatically~ #175
- [x] Edit flow: Editing an event updates the metadata of original event and deletes new edit event (to preserve page URL)
- [x] Rebuild search index automatically after approving an edited event (from #126)
- [x] Send email saying an edited event was approved or rejected (related to #134)

# Outcome

Provider users can successfully edit their own events.

**Comment by nlMeminger** [comment]
#175 finishes the auto load of metadata

**Comment by nlMeminger** [comment]
I would consider this completed.
