### ISSUE TITLE
BE Story: Configure critical information from a config file

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#157]
# Summary

Configure critical information for deploying the application in a config file

# Background

Certain information will change in a production environment. We want to ensure this information can be changed easily by the sponsor when they deploy the application. Putting it in a config file, so they don't have to change application code, makes it easier for them to configure the application to their needs.

# Details

- [x] ~SMTP server settings~ #179
- [x] ~Database settings~ #66
- [x] ~Initial admin email~ #163
- [x] ~Organization contact info (to show in the footer / about page)~ #205
- [x] ~Site name / FQDN~ #202

# Outcome

Sponsor can use their own SMTP servers, databases, and other deployment-specific config settings without editing project code
