### ISSUE TITLE
Docs Update

### ISSUE THREAD

**Issue by ldidonato** [jwflory/django-rit-grasa#166]
From the clean build section:

- [x] change `docker exec -it [containerID for the mariadb container]` to `docker exec -it [containerID for the mariadb container] /bin/bash` #165
- [x] change `docker exec -it [containerID for the django container]` to `docker exec -it [containerID for the django container] /bin/bash` #165
- [x] `makemigratons` is spelled wrong it needs to be `makemigrations` #165
- [x] make a note that you need to navigate to login page because there's an error with no events in db on search page, so to hit the header buttons you need to be at /login #165

**Comment by ldidonato** [comment]
> make a note that you need to navigate to login page because there's an error with no events in db on search page, so to hit the header buttons you need to be at /login

this has been fixed with the addition of the rebuild index command

**Comment by justwheel** [comment]
Cool, thanks for catching that @ldidonato. Closing as done. Thanks @leong96 for jumping on this! :clapper:
