### ISSUE TITLE
New documentation: Add user feature documentation

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#191]
# Summary

Write new user documentation to explain primary features and how to use them effectively

# Background

We did a lot of hard work to make this app possible but there are some inevitable quirks that we won't have time to polish up. Effective documentation will help train our users on common operations and help inform users of a "tried and tested" way of doing things, in case it is not obvious to us at the current point in time.

# Details

I was thinking to walk through each major feature on the [project success matrix](https://docs.google.com/spreadsheets/d/1cVUrC3E7bcSdZGAGF34moIWlVNoYZVwm_578x2HDY6Q/edit?usp=sharing) and create a new page for each major feature. Each feature page explains more complex tasks and operations around using the application. I intend to write this in a knowledgebase-style, e.g. Q&A format:

**Base system**:

- [x] ~~Update email.~~ #211 
- [x] ~~Change account password.~~ #211

**Event Curation System**:

- [x] ~~Register new provider account.~~ #214
- [x] ~~Create new event as a provider.~~ #214
- [x] ~~Edit an existing event as a provider.~~ #214
- [x] ~~How to approve an account.~~ #217
- [x] ~~How to approve a new event.~~ #217
- [x] ~~How to approve an event edit.~~ #217
- [x] ~~How to invite a Provider to register.~~ #217

**Search System**:

- [x] ~~How to search (with/without filters).~~ #233
- [x] ~~Share an event (i.e. send the URL).~~ #233

# Outcome

Clear user documentation to explain expected use; written for minimum two, potentially three audiences:

- **Providers**
- **Admin users**
- Potentially **family users**

**Comment by justwheel** [comment]
The Base System and Event Curation System documentation is done. I won't have time to get the Search System documentation by our meeting with GRASA today. **I pushed this task to the Bonus Sprint**, but the remaining Search System documentation is only two pages, so I am not that worried about on-time delivery before the hard hand-off on Nov. 28th.
