### ISSUE TITLE
New documentation: Add admin documentation

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#192]
# Summary

Write new documentation for system administrators who will manage and support the installation at a technical level

# Background

While end-user docs are important, we also need to remember our sysadmins. We need documentation to explain how to manage and support the application as much as possible. This reduces the difficulty in adopting our application and helps us better guarantee that our app actually gets deployed for real.

# Details

@nlMeminger has been running a staging site for some time to build the site, so he has a better idea of how to run the app in a non-production environment. We can standardize our documentation based on best practices of how the app is deployed today.

I was thinking to divide admin documentation by these pages, following the example of [another popular open source project's admin guide](https://sylabs.io/guides/3.2/admin-guide/):

- [x] ~~@nlMeminger Admin Quickstart (includes installation and configuration) (#122)~~ #226
- [x] ~~@jwflory Architecture diagrams~~ #239
- [x] ~~@nlMeminger How to update grasa_event_locator~~ #249

# Outcome

* Easier for future admins to manage and support our app
* Gives us a better shot that our code will get deployed beyond the course project

**Comment by justwheel** [comment]
The only thing left on this ticket is a short one-pager on the expected process to update the code and deploy changes to the Event Locator. @nlMeminger and I discussed this last week in the Ops meeting and I think he has an idea of how to tackle this. This is due by the Documentation Freeze on Friday, 29 November, but let's try to get it done by Wednesday so we can enjoy the Thanksgiving holiday without project stress over our heads.

**Comment by nlMeminger** [comment]
This is (finally) completed in #249
