### ISSUE TITLE
BE Story: Project polish and back-end improvements

### ISSUE THREAD

**Issue by justwheel** [jwflory/django-rit-grasa#64]
# Summary

Miscellaneous polish and improvements to back-end code now that all major features implemented

# Background

@eguy006 wanted to shift off of new feature development to focus on some polish and improvements to the back-end code. These are a mixed assortment of smaller tasks and items to improve the user experience.

# Details

- [x] ~Add UX to notify users of pending account status after new registration~ #112
- [x] ~Refactor "Fees" filter to use a double instead of a string~ #86
- [x] ~Compute distance between two pairs of latitude/longitude coordinates~ #148
- [x] ~Make search page the default home page~ #42, #110
- [x] ~Admin can delete other users~ #148

# Outcome

- More seamless user experience for our web app
- Easier to navigate around the application without hitting Django error pages

**Comment by justwheel** [comment]
@eguy006 got most of these things in #148. All remaining items are complete. Closing as complete! :ocean:
